### ISSUE TITLE
0 visited profiles

### ISSUE THREAD

**Issue by hista** [XenoX/AdopteUnMecBOT#2]
Hi, the script was perfectly working, until now:

```
python3 main.py 
Connected
Go to page https://www.adopteunmec.com/gogole?q=femme+de+moins+de+99+ans
0 visited profiles
```

Any idea why?

**Comment by XenoX** [comment]
Hello,

Thanks for your issue.

Fixed in https://github.com/XenoX/AdopteUnMecBOT/commit/b5676cad98c737a4b41f853ea4b0a2b3b1a72fd1

**Comment by hista** [comment]
Thanks for your fix, it's perfectly working again now!

**Comment by hista** [comment]
Sorry XenoX, this very same issue is back. 
Could you please tell me how to fix it?
